language: node_js
node_js: "stable"
after_success:
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec src/*tests.js && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage